### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by shivahnshankar** [hufan-Akari/BookLibrary#54]
Hi
I am beginner Python learner and i would love to use and if possible customise this eventually. Is there an easy way to change the UI language to English?
Thanks

**Comment by itchygrub** [comment]
Hi!

I am beginner.
Installed from git to Pycharm python 3.8
Is there way to translate
does it create a database
fixed typo's
when  run get this
Traceback (most recent call last):
  File "F:/PYCharm_Projects/BookLibrary/run.py", line 1, in <module>
    from app import app
  File "F:\PYCharm_Projects\BookLibrary\app\__init__.py", line 3, in <module>
    from flask_sqlalchemy import SQLAlchemy
  File "F:\PYCharm_Projects\mysite\venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 13, in <module>
    import sqlalchemy
  File "F:\PYCharm_Projects\mysite\venv\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "F:\PYCharm_Projects\mysite\venv\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "F:\PYCharm_Projects\mysite\venv\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "F:\PYCharm_Projects\mysite\venv\lib\site-packages\sqlalchemy\util\compat.py", line 331, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

**Comment by itchygrub** [comment]
Hi!
Have converted the Chinese text to English.
Still have the problems as per the last post

**Comment by faudard** [comment]
HI! I have done a translation in english by google trad

https://github.com/faudard/BookLibrary 

Enjoy !
